apiVersion: v1
kind: PersistentVolume
metadata:
  name: main-smb-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: main-smb-pvc
    namespace: default
  csi:
    driver: smb.csi.k8s.io
    nodeStageSecretRef:
      name: smb-creds
      namespace: default
    volumeAttributes:
      source: //nas.swage/Main
    volumeHandle: main-smb-vol-1
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=3.0
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

