---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack-cephfs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: 0001-0024-6f1b27de-7ad8-4953-91e0-a8fe3acec547-0000000000000001-bookstack
    nodeStageSecretRef:
      name: csi-cephfs-k3s-secret
      namespace: default
    volumeAttributes:
      clusterID: "6f1b27de-7ad8-4953-91e0-a8fe3acec547"
      fsName: "cephfs"
      staticVolume: "true"
      rootPath: "/k3s/bookstack"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-cephfs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: bookstack-cephfs-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstack
  namespace: default
  labels:
    app: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
        app.kubernetes.io/name: bookstack
    spec:
      containers:
      - name: bookstack
        image: linuxserver/bookstack:latest
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 3
        ports:
        - containerPort: 80
        env:
        - name: APP_URL
          value: "https://bookstack.swages.cloud"
        # Load DB_HOST, DB_USER, DB_PASS, & DB_DATABASE from secret
        envFrom:
        - secretRef:
            name: bookstack-secrets
            optional: false
        volumeMounts:
        - mountPath: "/config"
          name: bookstack-config
      volumes:
      - name: bookstack-config
        persistentVolumeClaim:
          claimName: bookstack-cephfs-pvc
