---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config-settings
  namespace: default # Make sure to use the correct namespace
data:
  settings.yaml: |
    cardBlur: md
    color: green
    favicon: /images/favicon.png
    layout:
      - Media:
          columns: 3
          style: row
      - Websites:
          rows: 1
          style: column
      - Networking:
          columns: 1
          style: column
      - Virtual Machines:
          columns: 3
          style: row
    theme: dark
    title: Swage's Homepage
