apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 10m
  # This should reference a HelmRepository or OCIRepository source you have defined.
  chartRef:
    kind: OCIRepository
    name: homepage
    namespace: default
  values:
    # Your existing values are correct
    enableRbac: true
    env:
      - name: LOG_LEVEL
        value: debug
      - name: PORT
        value: "3000"
      - name: TZ
        value: America/New_York
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: swages.cloud,www.swages.cloud,homepage.swages.cloud,swages.net,www.swages.net,homepage.swages.net
    image:
      pullPolicy: Always
      repository: ghcr.io/gethomepage/homepage
      tag: latest
    ingress:
      enabled: true
      className: traefik
      annotations:
        gethomepage.dev/description: You're currently on this page!
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Websites & Services
        gethomepage.dev/icon: homepage.png
        gethomepage.dev/name: Homepage
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
      hosts:
      - host: homepage.swages.cloud
        paths:
        - path: /
          pathType: Prefix
      - host: swages.cloud
        paths:
        - path: /
          pathType: Prefix
      - host: www.swages.cloud
        paths:
        - path: /
          pathType: Prefix
      - host: homepage.swages.net
        paths:
        - path: /
          pathType: Prefix
      - host: swages.net
        paths:
        - path: /
          pathType: Prefix
      - host: www.swages.net
        paths:
        - path: /
          pathType: Prefix
    persistence:
      icons:
        enabled: true
        type: nfs
        mountPath: /app/public/icons
        # All NFS settings are now nested under an 'nfs' key
        nfs:
          server: NAS.Swage
          path: /mnt/Raid-z2_Pool/NFS/homepage-data/icons # <-- Note: subPath is combined
          readOnly: false
      images:
        enabled: true
        type: nfs
        mountPath: /app/public/images
        nfs:
          server: NAS.Swage
          path: /mnt/Raid-z2_Pool/NFS/homepage-data/images # <-- Note: subPath is combined
          readOnly: false
    serviceAccount:
      create: true
      name: homepage

    config:
      bookmarks: {}
      docker: {}
      kubernetes: {}
      services: {}
      settings: {}
      widgets: {}

    volumes:
      - name: homepage-config-bookmarks
        configMap:
          name: homepage-config-bookmarks
      - name: homepage-config-docker
        configMap:
          name: homepage-config-docker
      - name: homepage-config-kubernetes
        configMap:
          name: homepage-config-kubernetes
      - name: homepage-config-services
        configMap:
          name: homepage-config-services
      - name: homepage-config-settings
        configMap:
          name: homepage-config-settings
      - name: homepage-config-widgets
        configMap:
          name: homepage-config-widgets

    volumeMounts:
      - name: homepage-config-bookmarks
        mountPath: /app/config/bookmarks.yaml
        subPath: bookmarks.yaml
      - name: homepage-config-docker
        mountPath: /app/config/docker.yaml
        subPath: docker.yaml
      - name: homepage-config-kubernetes
        mountPath: /app/config/kubernetes.yaml
        subPath: kubernetes.yaml
      - name: homepage-config-services
        mountPath: /app/config/services.yaml
        subPath: services.yaml
      - name: homepage-config-settings
        mountPath: /app/config/settings.yaml
        subPath: settings.yaml
      - name: homepage-config-widgets
        mountPath: /app/config/widgets.yaml
        subPath: widgets.yaml
