apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config-widgets
  namespace: default # Make sure to use the correct namespace
data:
  widgets.yaml: |
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
    - search:
        provider: google
        target: _blank
    - openmeteo:
        cache: 5
        label: Home
        latitude: 35.70897768322011
        longitude: -79.03597575118353
        timezone: America/New_York
        units: imperial
