apiVersion: apps/v1
kind: Deployment
metadata:
  # This name must match your Helm release name.
  name: homepage
spec:
  template:
    spec:
      containers:
        # Use a wildcard for the container name to make it more robust.
        - name: "*"
          volumeMounts:
            # Find the volumeMount named 'config' and delete it.
            - name: config
              $patch: delete
      volumes:
        # Find the volume named 'config' and delete it.
        - name: config
          $patch: delete
  