---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: blog
  namespace: flux-system
spec:
  image: ghcr.io/swage590/blog
  interval: 5m0s
  secretRef:
    name: ghcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog-latest-date-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blog
  filterTags:
    # This pattern now matches the YR.MO.DY.HR.MN.SC format
    pattern: '^(?P<timestamp>\d{2}\.\d{2}\.\d{2}\.\d{2}\.\d{2}\.\d{2})$'
    extract: '$timestamp'
  # Change the policy to semver to correctly sort the tags
  policy:
    alphabetical:
      order: desc
