---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: blog
  namespace: flux-system
spec:
  image: ghcr.io/swage590/blog
  interval: 5m0s
  secretRef:
    name: ghcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog-latest-date-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blog
  filterTags:
    # This pattern now captures each time segment individually
    pattern: '^(?P<y>\d{2})\.(?P<m>\d{2})\.(?P<d>\d{2})\.(?P<H>\d{2})\.(?P<M>\d{2})\.(?P<S>\d{2})$'
    # This extract line concatenates the captured groups without the dots
    extract: '$y$m$d$H$M$S'
  # Change the policy to semver to correctly sort the tags
  policy:
    numerical:
      order: asc
