apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: homepage
  namespace: default
spec:
  interval: 5m0s
  url: oci://ghcr.io/m0nsterrr/helm-charts/homepage
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: helm-homepage
  namespace: flux-system
spec:
  providerRef:
    name: discord-flux-chan
  eventSeverity: info
  eventSources:
  - kind: HelmRepository
    name: homepage
  - kind: HelmChart
    name: default-homepage
  - kind: HelmRelease
    name: homepage
    namespace: default
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: homepage
    namespace: default
  values:
    config:
      bookmarks:
      - Bookmarks:
        - Homepage:
          - href: https://homepage.swages.cloud
            icon: /icons/bookstack_favicon.ico
        - Descry.tech:
          - href: https://descry.swages.cloud
            icon: /icons/descry_eye.png
        - Photoprism:
          - href: https://photoprism.swages.cloud
            icon: /icons/photoprism_logo.svg
      docker:
        swage-data-docker:
          host: data.swage
          port: 2375
        swage-prince-docker:
          host: prince.swage
          port: 2375
      kubernetes:
        mode: cluster
      services:
      - Websites & Services:
        - Descry.tech:
            container: descry
            description: Project made during the NC State 2023 Hackathon
            href: https://descry.swages.cloud
            icon: /icons/descry_eye.png
            server: swage-prince-docker
        - Bookstack:
            app: bookstack
            description: Documentation Wiki
            href: https://bookstack.swages.cloud
            icon: /icons/bookstack_favicon.ico
            namespace: default
        - Uptime Kuma:
            app: uptime-kuma
            description: Uptime Monitoring & Warning System
            href: https://status.swages.cloud/status/swage
            icon: /icons/uptime_favicon.svg
            namespace: default
            widget:
              slug: swage
              type: uptimekuma
              url: https://status.swages.cloud/
      - Backend:
        - Traefik:
            app: traefik
            description: You're connected through this Reverse Proxy!
            icon: /icons/traefik_favicon.png
        - MariaDB:
            container: mariadb-db-1
            description: Database Server
            icon: /icons/mariadb_favicon.ico
            server: swage-data-docker
        - Adminer:
            container: mariadb-adminer-1
            description: Database Manager
            icon: /icons/adminer_favicon.ico
            server: swage-data-docker
      - Media:
        - Emby:
            container: embyserver
            description: Media Server
            icon: /icons/emby_favicon.ico
            server: swage-prince-docker
            widget:
              enableBlocks: true
              enableNowPlaying: false
              key: 2eceba604dcc4c4c9505aa711d96ae50
              type: emby
              url: http://Prince.Swage:8096/
        - Prowlarr:
            container: prowlarr
            description: Indexer Manager
            icon: /icons/prowlarr_logo.png
            server: swage-prince-docker
            widget:
              key: 6847471311bf4b03ab6e9d692d3301c2
              type: prowlarr
              url: http://Prince.Swage:9696
        - Radarr:
            container: radarr
            description: Movie Manager
            icon: /icons/radarr_logo.png
            server: swage-prince-docker
            widget:
              key: af7f86816d894c3da3130553a7ac0ce7
              type: radarr
              url: http://Prince.Swage:7878
        - Sonarr:
            container: sonarr
            description: TV Show Manager
            icon: /icons/sonarr_logo.png
            server: swage-prince-docker
            widget:
              key: 88a79b95ae944895a393d86d0d2072e7
              type: sonarr
              url: http://Prince.Swage:8989
        - qBitTorrent:
            container: qbittorrent
            description: Torrent Client
            icon: /icons/qbittorrent_favicon.ico
            server: swage-prince-docker
        - Photoprism:
            app: photoprism
            description: Self-Hosted Google Photos!
            href: https://photoprism.swages.cloud/
            icon: /icons/photoprism_logo.svg
            namespace: default
      - Physical Hardware:
        - RTX.Swage:
            description: AI Research Machine, and daily driver rig
            icon: /icons/nocompromisegaming_rtx_icon.jpg
        - Raspberry Pi 4:
            description: Running DietPi (Operating System) & Home Assistant (Fancy IoT
              Controller for the lights and stuff)
            icon: /icons/home_assistant_favicon.ico
            ping: 10.59.30.2
        - Dell Poweredge R620:
            description: XCP-ng host, runs all the VMs & Kubernetes
            icon: /icons/dell_favicon.ico
            ping: xcp-ng.Swage
        - Ubiquiti Cloud Gateway Max:
            description: Does the job of a Router, IDS/IPS, NVR, and Door Controller
            icon: /icons/cloud_gateway_max.png
        - Cisco 250 Series Switch:
            description: Helps separate my network into VLANs
            icon: /icons/cisco_favicon.ico
            ping: Switch.Swage
        - Ubiquiti Switch Flex Mini 2.5G:
            description: Like the Cisco switch, but faster and cheaper
            icon: /icons/flex_mini.png
        - Ubiquiti Switch Flex:
            description: Heat resistant, supplies PoE to cameras/doorbells/locks
            icon: /icons/flex.png
      - Virtual Machines:
        - Xen Orchestra:
            description: Hypervisor Manager, can automatically backup VMs, and works with packer/terraform
            icon: /icons/xcp-ng-badge.png
            ping: 10.59.20.11
        - Cloud Gateway Max:
            description: Router, Firewall, IDS/IDP, NVR, Door Controller, and VPN
            icon: /icons/unifi.svg
            ping: router.swage
        - TrueNAS:
            description: TrueNAS Core running a smb share on a 6 drive raidz2
            icon: /icons/truenas_favicon.ico
            ping: nas.swages.net
            widget:
              key: 2-Q9rcaKZfJpggP3ViDHoNIRTAbJ2BpM2UGOImJxkik9teu8xjjd2SKe0EjOo5jdjd
              type: truenas
              url: https://nas.swages.net/
        - Ubuntu Mantic Minotaur:
            description: General Purpose Ubuntu Machine
            icon: /icons/ubuntu_mascot.png
            ping: Prince.Swage
        - Windows Server 2025:
            description: Soon to be Axed
            icon: /icons/microsoft.png
            ping: glass.swage
        - Data.Swage:
            description: Runs my Database, I try to not do anything too crazy here...
            icon: /icons/mariadb_favicon.ico
            ping: Data.Swage
      settings:
        cardBlur: md
        color: green
        favicon: /images/favicon.png
        layout:
        - Media:
            columns: 3
            style: row
        - Websites:
            rows: 1
            style: column
        - Networking:
            columns: 1
            style: column
        - Virtual Machines:
            columns: 3
            style: row
        theme: dark
        title: Swage's Homepage
      widgets:
      - kubernetes:
          cluster:
            cpu: true
            label: cluster
            memory: true
            show: true
            showLabel: true
          nodes:
            cpu: true
            memory: true
            show: true
            showLabel: true
      - search:
          provider: google
          target: _blank
      - openmeteo:
          cache: 5
          label: Home
          latitude: 35.70897768322011
          longitude: -79.03597575118353
          timezone: America/New_York
          units: imperial
    enableRbac: true
    env:
    - name: LOG_LEVEL
      value: debug
    - name: PORT
      value: "3000"
    - name: TZ
      value: America/New_York
    - name: HOMEPAGE_ALLOWED_HOSTS
      value: swages.cloud,www.swages.cloud,homepage.swages.cloud,swages.net,www.swages.net,homepage.swages.net
    image:
      pullPolicy: Always
      repository: ghcr.io/gethomepage/homepage
      tag: latest
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          gethomepage.dev/description: You're currently on this page!
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Websites & Services
          gethomepage.dev/icon: homepage.png
          gethomepage.dev/name: Homepage
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
        hosts:
        - host: homepage.swages.cloud
          paths:
          - path: /
            pathType: Prefix
        - host: swages.cloud
          paths:
          - path: /
            pathType: Prefix
        - host: www.swages.cloud
          paths:
          - path: /
            pathType: Prefix
        - host: homepage.swages.net
          paths:
          - path: /
            pathType: Prefix
        - host: swages.net
          paths:
          - path: /
            pathType: Prefix
        - host: www.swages.net
          paths:
          - path: /
            pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /app/public/icons
        path: /mnt/Raid-z2_Pool/NFS
        readOnly: false
        server: NAS.Swage
        subPath: ./homepage-data/icons
        type: nfs
      images:
        enabled: true
        mountPath: /app/public/images
        path: /mnt/Raid-z2_Pool/NFS
        readOnly: false
        server: NAS.Swage
        subPath: ./homepage-data/images
        type: nfs
    serviceAccount:
      create: true
      name: homepage
