apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  url: https://dirsigler.github.io/metallb-helm
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: helm-metallb
  namespace: flux-system
spec:
  providerRef:
    name: discord-flux-chan
  eventSeverity: info
  eventSources:
  - kind: HelmRepository
    name: metallb
  - kind: HelmChart
    name: default-metallb
  - kind: HelmRelease
    name: metallb
    namespace: metallb-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 10m
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
    values:
      configInline:
        address-pools:
          - name: default
            protocol: layer2
            addresses:
              - 10.59.20.70-10.59.20.79
