apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: photoprism
spec:
  selector:
    matchLabels:
      app: photoprism
  serviceName: photoprism
  replicas: 1
  template:
    metadata:
      labels:
        app: photoprism
        name: photoprism
        app.kubernetes.io/name: photoprism
    spec:
      containers:
      - name: photoprism
        image: photoprism/photoprism:latest
        env:
        - name: PHOTOPRISM_DATABASE_DRIVER
          value: mysql
        - name: PHOTOPRISM_HTTP_HOST
          value: 0.0.0.0
        - name: PHOTOPRISM_HTTP_PORT
          value: "2342"
        # Load database DSN & admin password from secret
        envFrom:
        - secretRef:
            name: photoprism-secrets
            optional: false
        ports:
        - containerPort: 2342
          name: http
        volumeMounts:
        - mountPath: /photoprism/originals
          name: smb-main
          subPath: Home-Lab/Photos
        - mountPath: /photoprism/storage
          name: smb-main
          subPath: Home-Lab/Kubernetes/Photoprism
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: http
      volumes:
      - name: smb-main
        persistentVolumeClaim:
          claimName: main-smb-pvc
