apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-originals-pv
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime
    - rasize=33554432
    - wsize=33554432
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: 0001-0024-6f1b27de-7ad8-4953-91e0-a8fe3acec547-0000000000000001-photoprism-originals
    nodeStageSecretRef:
      name: csi-cephfs-sharedrive-secret
      namespace: default
    volumeAttributes:
      clusterID: "6f1b27de-7ad8-4953-91e0-a8fe3acec547"
      fsName: "cephfs"
      staticVolume: "true"
      rootPath: "/sharedrive/Media/Photos"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-originals-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
  volumeName: photoprism-originals-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-storage-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: photoprism
  namespace: default
spec:
  selector:
    matchLabels:
      app: photoprism
  serviceName: photoprism
  replicas: 1
  template:
    metadata:
      labels:
        app: photoprism
        name: photoprism
        app.kubernetes.io/name: photoprism
    spec:
      containers:
      - name: photoprism
        image: photoprism/photoprism:latest
        env:
        - name: PHOTOPRISM_DATABASE_DRIVER
          value: mysql
        - name: PHOTOPRISM_HTTP_HOST
          value: 0.0.0.0
        - name: PHOTOPRISM_HTTP_PORT
          value: "2342"
        # Load database DSN & admin password from secret
        envFrom:
        - secretRef:
            name: photoprism-secrets
            optional: false
        ports:
        - containerPort: 2342
          name: http
        volumeMounts:
        - mountPath: /photoprism/originals
          name: photoprism-originals
        - mountPath: /photoprism/storage
          name: photoprism-storage
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: http
      volumes:
      - name: photoprism-originals
        persistentVolumeClaim:
          claimName: photoprism-originals-pvc
      - name: photoprism-storage
        persistentVolumeClaim:
          claimName: photoprism-storage-pvc
